### ISSUE TITLE
Question: does this support JavaScript?

### ISSUE THREAD

**Issue by freekmurze** [nealio82/PHPStorm-GitHub-Theme#1]
Hi, 

this seems like an awesome theme. I noticed that there isn't a JavaScript screenshot in the readme. Does this color theme provide good colors for JavaScript files?

**Comment by nealio82** [comment]
Not yet...

I've been meaning to but haven't got around to it yet. I'll see if I can find some time to add JS by the weekend

**Comment by bbashy** [comment]
Always wanted to find a great light theme. JS is needed for me too!

**Comment by freekmurze** [comment]
@bbashy It already looks fairly good in it's current state. 👍

**Comment by nealio82** [comment]
This theme now supports JS (as close as I could get it). It looks like the CSS-in-JS styling is inherited from the CSS highlighting component, so to get a closer match the CSS syntax highlighting will also need to be modified
